-- MySQL Script generated by MySQL Workbench
-- Thu Sep 25 22:19:16 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `customers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `customers` ;

CREATE TABLE IF NOT EXISTS `customers` (
  `customer_id` INT NOT NULL AUTO_INCREMENT,
  `full_name` VARCHAR(200) NOT NULL,
  `birth_date` DATE NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `phone` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`customer_id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `addresses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `addresses` ;

CREATE TABLE IF NOT EXISTS `addresses` (
  `address_id` INT NOT NULL AUTO_INCREMENT,
  `customer_id` INT NOT NULL,
  `line1` VARCHAR(255) NOT NULL,
  `line2` VARCHAR(255) NULL,
  `city` VARCHAR(120) NOT NULL,
  `postal_code` VARCHAR(20) NOT NULL,
  `country` VARCHAR(120) NOT NULL,
  PRIMARY KEY (`address_id`),
  INDEX `fk_addresses_customer_idx` (`customer_id` ASC) VISIBLE,
  CONSTRAINT `fk_addresses_customer`
    FOREIGN KEY (`customer_id`)
    REFERENCES `customers` (`customer_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizzas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pizzas` ;

CREATE TABLE IF NOT EXISTS `pizzas` (
  `pizza_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(120) NOT NULL,
  `active` TINYINT(1) NOT NULL,
  PRIMARY KEY (`pizza_id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ingredients`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ingredients` ;

CREATE TABLE IF NOT EXISTS `ingredients` (
  `ingredient_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(120) NOT NULL,
  `cost_per_unit` DECIMAL(10,2) NOT NULL,
  `unit` VARCHAR(16) NOT NULL,
  `is_meat` TINYINT(1) NOT NULL,
  `is_animal_product` TINYINT(1) NOT NULL,
  PRIMARY KEY (`ingredient_id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizza_ingredients`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pizza_ingredients` ;

CREATE TABLE IF NOT EXISTS `pizza_ingredients` (
  `pizza_id` INT NOT NULL,
  `ingredient_id` INT NOT NULL,
  `qty_unit` DECIMAL(10,2) NOT NULL,
  INDEX `fk_pi_ingredient_idx` (`ingredient_id` ASC) VISIBLE,
  PRIMARY KEY (`pizza_id`, `ingredient_id`),
  CONSTRAINT `fk_pi_pizza`
    FOREIGN KEY (`pizza_id`)
    REFERENCES `pizzas` (`pizza_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_pi_ingredient`
    FOREIGN KEY (`ingredient_id`)
    REFERENCES `ingredients` (`ingredient_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `drinks`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `drinks` ;

CREATE TABLE IF NOT EXISTS `drinks` (
  `drink_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(120) NOT NULL,
  `unit_price` DECIMAL(10,2) NOT NULL,
  `vegan` TINYINT(1) NOT NULL,
  PRIMARY KEY (`drink_id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `desserts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `desserts` ;

CREATE TABLE IF NOT EXISTS `desserts` (
  `dessert_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(120) NOT NULL,
  `unit_price` DECIMAL(10,2) NOT NULL,
  `vegan` TINYINT(1) NOT NULL,
  PRIMARY KEY (`dessert_id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `discount_codes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `discount_codes` ;

CREATE TABLE IF NOT EXISTS `discount_codes` (
  `discount_code_id` INT NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(64) NOT NULL,
  `percent_off` DECIMAL(5,2) NOT NULL,
  `single_use` TINYINT(1) NOT NULL,
  `redeemed_at` DATETIME NULL,
  `redeemed_by_customer` INT NULL,
  PRIMARY KEY (`discount_code_id`),
  UNIQUE INDEX `code_UNIQUE` (`code` ASC) VISIBLE,
  INDEX `fk_dc_redeemed_by_idx` (`redeemed_by_customer` ASC) VISIBLE,
  CONSTRAINT `fk_dc_redeemed_by`
    FOREIGN KEY (`redeemed_by_customer`)
    REFERENCES `customers` (`customer_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `orders`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `orders` ;

CREATE TABLE IF NOT EXISTS `orders` (
  `order_id` INT NOT NULL AUTO_INCREMENT,
  `customer_id` INT NOT NULL,
  `address_id` INT NOT NULL,
  `placed_at` DATETIME NOT NULL,
  `status` ENUM('PLACED', 'PREPARING', 'OUT_FOR_DELIVERY', 'DELIVERED', 'CANCELLED') NOT NULL,
  `discount_code_id` INT NULL,
  PRIMARY KEY (`order_id`),
  INDEX `fk_orders_customer_idx` (`customer_id` ASC) VISIBLE,
  INDEX `fk_orders_address_idx` (`address_id` ASC) VISIBLE,
  INDEX `fk_orders_discount_idx` (`discount_code_id` ASC) VISIBLE,
  CONSTRAINT `fk_orders_customer`
    FOREIGN KEY (`customer_id`)
    REFERENCES `customers` (`customer_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_orders_address`
    FOREIGN KEY (`address_id`)
    REFERENCES `addresses` (`address_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_orders_discount`
    FOREIGN KEY (`discount_code_id`)
    REFERENCES `discount_codes` (`discount_code_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `order_pizzas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `order_pizzas` ;

CREATE TABLE IF NOT EXISTS `order_pizzas` (
  `order_id` INT NOT NULL,
  `pizza_id` INT NOT NULL,
  `size` ENUM('S', 'M', 'L') NOT NULL,
  `quantity` INT NOT NULL,
  PRIMARY KEY (`order_id`, `pizza_id`, `size`),
  INDEX `fk_op_pizza_idx` (`pizza_id` ASC) VISIBLE,
  CONSTRAINT `fk_op_order`
    FOREIGN KEY (`order_id`)
    REFERENCES `orders` (`order_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_op_pizza`
    FOREIGN KEY (`pizza_id`)
    REFERENCES `pizzas` (`pizza_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `order_drinks`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `order_drinks` ;

CREATE TABLE IF NOT EXISTS `order_drinks` (
  `order_id` INT NOT NULL,
  `drink_id` INT NOT NULL,
  `quantity` INT NOT NULL,
  PRIMARY KEY (`order_id`, `drink_id`),
  INDEX `fk_od_drink_idx` (`drink_id` ASC) VISIBLE,
  CONSTRAINT `fk_od_order`
    FOREIGN KEY (`order_id`)
    REFERENCES `orders` (`order_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_od_drink`
    FOREIGN KEY (`drink_id`)
    REFERENCES `drinks` (`drink_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `order_desserts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `order_desserts` ;

CREATE TABLE IF NOT EXISTS `order_desserts` (
  `order_id` INT NOT NULL,
  `dessert_id` INT NOT NULL,
  `quantity` INT NOT NULL,
  PRIMARY KEY (`order_id`, `dessert_id`),
  INDEX `fk_oe_dessert_idx` (`dessert_id` ASC) VISIBLE,
  CONSTRAINT `fk_oe_order`
    FOREIGN KEY (`order_id`)
    REFERENCES `orders` (`order_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_oe_dessert`
    FOREIGN KEY (`dessert_id`)
    REFERENCES `desserts` (`dessert_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `delivery_people`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `delivery_people` ;

CREATE TABLE IF NOT EXISTS `delivery_people` (
  `delivery_person_id` INT NOT NULL AUTO_INCREMENT,
  `full_name` VARCHAR(200) NOT NULL,
  `phone` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`delivery_person_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `delivery_zones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `delivery_zones` ;

CREATE TABLE IF NOT EXISTS `delivery_zones` (
  `delivery_person_id` INT NOT NULL,
  `postal_code` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`delivery_person_id`, `postal_code`),
  CONSTRAINT `fk_dz_person`
    FOREIGN KEY (`delivery_person_id`)
    REFERENCES `delivery_people` (`delivery_person_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `deliveries`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `deliveries` ;

CREATE TABLE IF NOT EXISTS `deliveries` (
  `order_id` INT NOT NULL,
  `assigned_to` INT NOT NULL,
  `assigned_at` DATETIME NOT NULL,
  `delivered_at` DATETIME NULL,
  PRIMARY KEY (`order_id`),
  INDEX `fk_delivery_person_idx` (`assigned_to` ASC) VISIBLE,
  CONSTRAINT `fk_delivery_order`
    FOREIGN KEY (`order_id`)
    REFERENCES `orders` (`order_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_delivery_person`
    FOREIGN KEY (`assigned_to`)
    REFERENCES `delivery_people` (`delivery_person_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
